WebApp/ToLetTrackerWeb/tolettracker/tolet/urls.py
from django.urls import path
from tolet import views

# URL's that's within the "tolet" app
app_name = "tolet"
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('home/', views.home, name='home'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('home/profile/', views.profile, name='profile'),
    path('home/listings/', views.listings, name='listings'),
    path('home/listings/listings_form/', views.listings_form, name='listings_form'),
    path('home/listings/listings_list/', views.listings_list, name='listings_list'),
    path('home/settings/', views.settings, name='settings'),
    path('graphql/query/', views.query, name='query'),
]

WebApp/ToLetTrackerWeb/tolettracker/tolettracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from tolet import views
from . import  settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from graphene_django.views import GraphQLView
from .schema import schema

#URL's of Main Project
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tolet.urls')),

    path('graphql/', GraphQLView.as_view(
        graphiql=True,
        schema=schema
    ), name='graphql'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="tolet/password_reset.html"), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="tolet/reset_password_sent.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="tolet/password_reset_form.html"), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="tolet/password_reset_done.html"), name='password_reset_complete'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_DIR)

WebApp/ToLetTrackerWeb/tolettracker/tolet/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# User Profile Model
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

# FLat Information Model
class FlatListingInfo(models.Model):
    userprofileinfo = models.ForeignKey(UserProfileInfo, on_delete=models.CASCADE)
    phone_number = PhoneNumberField(max_length=14)
    location = models.CharField(max_length=100)
    longitude = models.FloatField(default=0.0, blank=True)
    latitude = models.FloatField(default=0.0, blank=True)
    flat_description = models.CharField(max_length=2000)
    flat_size = models.PositiveIntegerField(default=0)
    total_rent = models.PositiveIntegerField(default=0)
    post_time = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    photos = models.ImageField(upload_to='images/flats', blank=True)

    def __str__(self):
        return str(self.userprofileinfo.user)


def create_user(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfileInfo.objects.create(user=kwargs['instance'])

post_save.connect(create_user, sender=User)

WebApp/ToLetTrackerWeb/tolettracker/tolet/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm 
from .models import UserProfileInfo, FlatListingInfo

# User Details Form
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password',)


class EditProfile(UserChangeForm):
    class Meta():
        model=User
        fields = ('first_name', 'last_name', 'email',)
        exclude = ()

# FLat Information Form
class EditDetails(forms.ModelForm):
    class Meta():
        model = FlatListingInfo
        fields = ('phone_number', 'location', 'longitude', 'latitude', 'flat_description', 'flat_size', 'total_rent', 'is_active', 'photos',)

WebApp/ToLetTrackerWeb/tolettracker/tolet/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import UserForm, EditProfile, EditDetails
from django.contrib import messages
from .models import UserProfileInfo, FlatListingInfo
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm

# The Initial View
def index(request):
    return render(request, 'tolet/index.html')

# Home/Dashboard View
@login_required
def home(request):
    return render(request, "tolet/home.html")

# User Registration View
def register(request):
    if request.user.is_authenticated:
        return redirect('tolet:home')
    else:
        if request.method == "POST":
            user_form = UserForm(data = request.POST)

            if user_form.is_valid():
                user = user_form.save()
                user.set_password(user.password)
                user.save()
                username = user_form.cleaned_data.get('username')
                messages.success(request, "Account created successfully for " + username +" 🎈")
                return HttpResponseRedirect(reverse('tolet:user_login'))
            else:
                print(user_form.errors)
        else:
            user_form = UserForm()
        return render(request, 'tolet/registration.html', {'user_form':user_form})

# User Login View
def user_login(request):
    if request.user.is_authenticated:
        return redirect('tolet:home')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    print("\nUsername: {}, Passoword: {}, Authenticated!\n".format(username, password))
                    return redirect('tolet:home')
                else:
                    print("\nUsername: {}, Account is not active!\n".format(username))
            else:
                messages.info(request, "Username or Password is incorrect")
                print("\nUsername: {}, Passoword: {}, Not Authenticated!\n".format(username, password))
                return redirect('tolet:user_login')
        else:
            return render(request, 'tolet/login.html')

# User Logout View
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('tolet:index'))

# User Profile View
@login_required
def profile(request):
    if request.method=='POST':
        form = EditProfile(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('tolet:home')
    else:
        form = EditProfile(instance=request.user)
        context = {
            'form': form
            }
        return render(request, 'tolet/profile.html',context)

# User Listing View
@login_required
def listings(request):
    return render(request, 'tolet/listings.html')

# User Add Listing View
@login_required
def listings_form(request):
    if request.method=='POST':
        form = EditDetails(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, request.user)
            messages.success(request, "Listing has been created! 🌐")
            return redirect('tolet:listings_list')
        else:
            print(form.errors)
            messages.error(request, "Listing couldn't be posted! 🛑")
            return render(request, 'tolet/listings_form.html')
    else:
        form = EditDetails(request.POST)
        context = {
            'form':form
        }
        return render(request, 'tolet/listings_form.html', context)

# User Check Listing View
@login_required
def listings_list(request):
    form = EditDetails()
    flat_listing = FlatListingInfo.objects.all()
    
    context = {
        'form': form,
        'flats': flat_listing
    }
    return render(request, 'tolet/listings_list.html', context)

# User Settings View
@login_required
def settings(request):
    if request.method=='POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, "Password successfully changed for " + request.user.username + " ✅")
            return redirect('tolet:home')
        else:
            messages.error(request, "Error in password changing ❌")
            return render(request, 'tolet/settings.html')
    else:
        form = PasswordChangeForm(user=request.user)
        context = {
            'form': form
            }
        return render(request, 'tolet/settings.html', context)

# GraphQL View
def query(request):
    return render(request, 'tolet/query.html')

WebApp/ToLetTrackerWeb/tolettracker/templates/tolet/home.html
// The Home View

<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>
    <title>Home - {{request.user.username}}</title>
</head>
<body>
    {% block bodyblock %}
    <div class="jumbotron container" style="text-align: center;">
        <h3>Welcome to ToLet Tracker, {{request.user.username}}! 🎉🎊</h3>
        <br><br>
        {% for message in messages %}
		    <h4 id="messages">{{message}}</h4>
		{% endfor %}
        
    </div>
    {% endblock %}


<div class="container">
	<div class="row">
		<div class="col-md-3 ">
		     <div class="list-group ">
                {% if user.is_authenticated %}
                    <a href="{% url 'tolet:home' %}" class="list-group-item list-group-item-action active">Dashboard</a>
                    <a href="{% url 'tolet:profile' %}" class="list-group-item list-group-item-action">Profile</a>
                    <a href="{% url 'tolet:listings' %}" class="list-group-item list-group-item-action">Listings</a>
                    <a href="{% url 'tolet:settings' %}" class="list-group-item list-group-item-action">Settings</a>
                    <a href="{% url 'tolet:user_logout' %}" class="list-group-item list-group-item-action">Logout</a>
                {% endif %}
              
              
            </div> 
		</div>
		<div class="col-md-9">
		    <div class="card">
		        <div class="card-body">
		            <div class="row">
		                <div class="col-md-12">
		                    <h4>Your Profile</h4>
		                    <hr>
		                </div>
		            </div>
		            <div class="row">
		                <div class="col-md-12">
		                    <div class="form-group row">
                               <label for="username" class="col-4 col-form-label">Username:</label> 
                               <div class="col-8">
                                  {{user.username}}
                               </div>
                              </div>
                              <div class="form-group row">
                                <label for="name" class="col-4 col-form-label">First Name:</label> 
                                <div class="col-8">
                                  {{user.first_name}}
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="lastname" class="col-4 col-form-label">Last Name:</label> 
                                <div class="col-8">
                                  {{user.last_name}}
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="email" class="col-4 col-form-label">Email:</label> 
                                <div class="col-8">
                                  {{user.email}}
                                </div>
                            </div>
		                </div>
		            </div>
		            
		        </div>
		    </div>
		</div>
	</div>
</div>

</body>
</html>

WebApp/ToLetTrackerWeb/tolettracker/templates/tolet/index.html
// The Index View

<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>
    <title>ToLet Tracker</title>
</head>
<body>
    <div class="container jumbotron" style="text-align: center;">
        <h1>Welcome to 🏡 ToLet Tracker 🏚</h1>
        <br><br>
        <h3>First time? -> <a href="{%url 'tolet:register'%}"><button>(❁´◡`❁)</button></a></h3>
        <br>
        <h3>Already have an account? -> <a href="{%url 'tolet:user_login'%}"><button>¯\_(ツ)_/¯</button></a></h3>
        <br>
        <h3>Want to go to a cool place? -> <a href="{%url 'admin:index' %}"><button>(¬‿¬)</button></a></h3>
    </div>
</body>
</html>

WebApp/ToLetTrackerWeb/tolettracker/templates/tolet/listings.html
// The Listings View

<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>
    <title>Settings</title>
</head>
<style>
    button{
        border-radius: 10px;
        padding: 10px 24px;
        border: 2px solid #74cfbf;
        background-color: white;
        transition-duration: 0.3s;
    }
    button:hover{
        background-color: #74cfbf;
        border: 2px solid white;
        color: white;
    }
</style>
<body>
    {% block bodyblock %}
    <div class="jumbotron container" style="text-align: center;">
        <h3>🏡 ToLet Tracker 🏚</h3>
        <br><br>
        {% for message in messages %}
		    <h4 id="messages">{{message}}</h4>
		{% endfor %}
    </div>
    {% endblock %}

<div class="container">
	<div class="row">
		<div class="col-md-3 ">
		     <div class="list-group ">
                {% if user.is_authenticated %}
                <a href="{% url 'tolet:home' %}" class="list-group-item list-group-item-action">Dashboard</a>
                <a href="{% url 'tolet:profile' %}" class="list-group-item list-group-item-action">Profile</a>
                <a href="{% url 'tolet:listings' %}" class="list-group-item list-group-item-action active">Listings</a>
                <div class="col-md-12">
                    <a href="{% url 'tolet:listings_form' %}" class="list-group-item list-group-item-action">Add Listings</a>
                    <a href="{% url 'tolet:listings_list' %}" class="list-group-item list-group-item-action">Check Listings</a>
                </div>
                <a href="{% url 'tolet:settings' %}" class="list-group-item list-group-item-action">Settings</a>
                {% endif %}
              
              
            </div> 
		</div>
		<div class="col-md-9">
		    <div class="card">
		        <div class="card-body">
		            <div class="row">
		                <div class="col-md-12" style="text-align: center;">                        
                            <h3>⬇ To <i>add</i> your ToLet Listing ⬇</h3><br>
                            <a href="{% url 'tolet:listings_form' %}"><button>Click Here</button></a>
                            <br><br>
                            <h3>⬇ To <i>check</i> your ToLet Listing ⬇</h3><br>
                            <a href="{% url 'tolet:listings_list' %}"><button>Click Here</button></a>
		                </div>
		            </div>
		        </div>
		    </div>
		</div>
    </div>
</div>
</body>
</html>

WebApp/ToLetTrackerWeb/tolettracker/templates/tolet/listings_form.html
// The Add Listing View

<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>
    <title>Add Listings</title>
</head>
<style>
  button{
    position:relative;
    top:50%; 
    left:40%;
    border-radius: 5px;
    padding: 8px 24px;
    border: 2px solid #74cfbf;
    background-color: white;
    transition-duration: 0.3s;
  }
    button:hover{
        background-color: #74cfbf;
        border: 2px solid white;
        color: white;
    }
</style>
<body>
    {% block bodyblock %}
    <div class="jumbotron container" style="text-align: center;">
        <h3>🏡 ToLet Tracker 🏚</h3>
        <br><br>
        <h4>❌❗ Broken - Needs More Time ❗❌</h4>
        <br><br>
        {% for message in messages %}
		    <h4 id="messages">{{message}}</h4>
		{% endfor %}
    </div>
    {% endblock %}

<div class="container">
	<div class="row">
		<div class="col-md-3 ">
		     <div class="list-group ">
                {% if user.is_authenticated %}
                <a href="{% url 'tolet:home' %}" class="list-group-item list-group-item-action">Dashboard</a>
                <a href="{% url 'tolet:profile' %}" class="list-group-item list-group-item-action">Profile</a>
                <a href="{% url 'tolet:listings' %}" class="list-group-item list-group-item-action">Listings</a>
                <div class="col-md-12">
                    <a href="{% url 'tolet:listings_form' %}" class="list-group-item list-group-item-action active">Add Listings</a>
                    <a href="{% url 'tolet:listings_list' %}" class="list-group-item list-group-item-action">Check Listings</a>
                </div>
                <a href="{% url 'tolet:settings' %}" class="list-group-item list-group-item-action">Settings</a>
                {% endif %}
              
              
            </div> 
		</div>
		<div class="col-md-9">
		    <div class="card">
		        <div class="card-body">
		            <div class="row">
		                <div class="col-md-12">                        
		                    <form method="POST" action="{% url 'tolet:listings_form' %}">
                                {% csrf_token %}
                                <div class="form-group row">
                                    <label for="phone_number" class="col-4 col-form-label">Phone Number:</label> 
                                    <div class="col-8">
                                        {{form.phone_number}}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="location" class="col-4 col-form-label">Location:</label> 
                                    <div class="col-8">
                                        {{form.location}}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="flat_description" class="col-4 col-form-label">Flat Description:</label> 
                                    <div class="col-8">
                                        {{form.flat_description}}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="flat_size" class="col-4 col-form-label">Flat Size (sqft):</label> 
                                    <div class="col-8">
                                        {{form.flat_size}}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="total_rent" class="col-4 col-form-label">Total Rent (BDT):</label> 
                                    <div class="col-8">
                                        {{form.total_rent}}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="photos" class="col-4 col-form-label">Photo (if any):</label> 
                                    <div class="col-8">
                                        {{form.photos}}
                                    </div>
                                </div>
                              <button type="submit">Change</button>                             
                            </form>
		                </div>
		            </div>
		            
		        </div>
		    </div>
		</div>
	</div>
</div>
</body>
</html>

WebApp/ToLetTrackerWeb/tolettracker/templates/tolet/listings_list.html
// The Check Listing View

<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>
    <title>Check Listings</title>
</head>
<style>
  button{
    position:relative;
    top:50%; 
    left:40%;
    border-radius: 5px;
    padding: 8px 24px;
    border: 2px solid #74cfbf;
    background-color: white;
    transition-duration: 0.3s;
    }
    button:hover{
        background-color: #74cfbf;
        border: 2px solid white;
        color: white;
    }
</style>
<body>
    {% block bodyblock %}
    <div class="jumbotron container" style="text-align: center;">
        <h3>🏡 ToLet Tracker 🏚</h3>
        <br><br>
        {% for message in messages %}
		    <h4 id="messages">{{message}}</h4>
		{% endfor %}
    </div>
    {% endblock %}

<div class="container">
	<div class="row">
		<div class="col-md-3 ">
		     <div class="list-group ">
                {% if user.is_authenticated %}
                <a href="{% url 'tolet:home' %}" class="list-group-item list-group-item-action">Dashboard</a>
                <a href="{% url 'tolet:profile' %}" class="list-group-item list-group-item-action">Profile</a>
                <a href="{% url 'tolet:listings' %}" class="list-group-item list-group-item-action">Listings</a>
                <div class="col-md-12">
                    <a href="{% url 'tolet:listings_form' %}" class="list-group-item list-group-item-action">Add Listings</a>
                    <a href="{% url 'tolet:listings_list' %}" class="list-group-item list-group-item-action active">Check Listings</a>
                </div>
                <a href="{% url 'tolet:settings' %}" class="list-group-item list-group-item-action">Settings</a>
                {% endif %}
              
              
            </div> 
		</div>
		<div class="col-md-9">
		    <div class="card">
		        <div class="card-body">
		            <div class="row">
		                <div class="col-md-12">                        
		                    <div class="form-group row">
                                <label for="username" class="col-2 col-form-label">Rent List</label>
                                <div class="col-8">
                                    {% for flat in flats %}
                                        <div class="form-group row">
                                            <label for="" class="col-6 col-form-label"><strong>Listing No: {{flat.id}}</strong></label> 
                                            <div class="col-12">
                                                {% if flat.is_active %}
                                                Status: Available ✔
                                                {% else %}
                                                Status: Not Available ❌
                                                {% endif %}
                                                <p></p>
                                                Location: {{flat.location}}
                                                <p></p>
                                                Description: <p>{{flat.flat_description}}</p>
                                                
                                                Contact Number: {{flat.phone_number}}
                                                <p></p>
                                                Flat Size (sqft): {{flat.flat_size}}
                                                <p></p>
                                                Total Rent (BDT): {{flat.total_rent}}/=
                                                <p></p>
                                                Photo: <img src="{{ flat.photos.url }}" width="500" alt="{{flat.location}}">
                                                <p><br><br></p>
                                                Posted On: {{flat.post_time}}
                                                <p>-------------------------------------</p><br>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
		                </div>
		            </div>		            
		        </div>
		    </div>
		</div>
	</div>
</div>
</body>
</html>

WebApp/ToLetTrackerWeb/tolettracker/templates/tolet/profile.html
// The User Profile View

<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>
    <title>Profile</title>
</head>
<style>
  button{
    position:relative;
    top:50%; 
    left:39%;
    border-radius: 5px;
    padding: 8px 24px;
    border: 2px solid #74cfbf;
    background-color: white;
    transition-duration: 0.3s;
  }
    button:hover{
        background-color: #74cfbf;
        border: 2px solid white;
        color: white;
    }
</style>
<body>
    {% block bodyblock %}
    <div class="jumbotron container">
        <h3 style="text-align: center;">🏡 ToLet Tracker 🏚</h3>
        <br><br>
    </div>
    {% endblock %}

<div class="container">
	<div class="row">
		<div class="col-md-3 ">
		     <div class="list-group ">
                {% if user.is_authenticated %}
                <a href="{% url 'tolet:home' %}" class="list-group-item list-group-item-action">Dashboard</a>
                <a href="{% url 'tolet:profile' %}" class="list-group-item list-group-item-action active">Profile</a>
                <a href="{% url 'tolet:listings' %}" class="list-group-item list-group-item-action">Listings</a>
                <a href="{% url 'tolet:settings' %}" class="list-group-item list-group-item-action">Settings</a>
                {% endif %}
              
              
            </div> 
		</div>
		<div class="col-md-9">
		    <div class="card">
		        <div class="card-body">
		            <div class="row">
		                <div class="col-md-12">
		                    <form method="POST">
                                {% csrf_token %}
                              <div class="form-group row">
                                <label for="first_name" class="col-4 col-form-label">First Name:</label> 
                                <div class="col-8">
                                  {{form.first_name}}
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="last_name" class="col-4 col-form-label">Last Name:</label> 
                                <div class="col-8">
                                  {{form.last_name}}
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="email" class="col-4 col-form-label">Email:</label> 
                                <div class="col-8">
                                  {{form.email}}
                                </div>
                              </div> 
                              {{form.errors}}                              
                              <button type="submit">Change</button>                             
                        </form>
                      		                </div>
		                </div>
		                </div>
		            </div>
		        </div>
		        </div>
		    </div>
		</div>
	</div>
</div>
</body>
</html>